[Homework #1](https://colab.research.google.com/github/Jaguar838/ml-zoomcamp/blob/master/HW/hw-01/hw-01.ipynb)

### Set up the environment

You need to install Python, NumPy, Pandas. For that, you can the instructions from <a href='https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/06-environment.md'>06-environment.md</a>.

In [14]:
!python -V

Python 3.10.12


In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

### Question 1

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [2]:
pd.__version__

'2.1.4'

### Getting the data

For this homework, we'll use the Laptops Price dataset. Download it from <a href='https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'>here</a>.

You can do it with wget:
```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
```
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [48]:
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

### Q2. Records count

How many records are in the dataset?

In [8]:
data.shape[0]

2160

### Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [21]:
unique_brands = data['Brand'].unique()
unique_brands

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [20]:
num_unique_brands = len(unique_brands)
num_unique_brands

27

In [15]:
data['Brand'].nunique()

27

### Q4. Missing values

How many columns in the dataset have missing values?

In [18]:
missing_columns = data.isnull().sum()
missing_columns

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [19]:
num_columns_with_missing = (missing_columns > 0).sum()
print("Number of columns with missing values:", num_columns_with_missing)

Number of columns with missing values: 3


### Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [23]:
dell_laptops = data[data['Brand'] == 'Dell']
dell_laptops

Laptop       Status Brand  \
161   Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...          New  Dell   
271   Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...          New  Dell   
281   Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...          New  Dell   
319   Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...          New  Dell   
328   Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...          New  Dell   
...                                                 ...          ...   ...   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
1844  Dell Vostro 5301 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1845  Dell Vostro 5502 Intel Core i5-1135G7/8GB/512G...  Refurbished  Dell   
1846  Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512G...  Refurbished  Dell   
1847  Dell XPS 7390 Intel Core i7-10510U/16GB/512GB ...  Refurbished  Dell   

         Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
161     Vostro  Intel Core i3    8      256          SSD  NaN    15.6    No   
271     Vostro  Intel Core i5    8      256          SSD  NaN    15.6    No   
281     Vostro  Intel Core i7   16      512          SSD  NaN    15.6    No   
319   Latitude  Intel Core i5    8      256          SSD  NaN    15.6    No   
328     Vostro  Intel Core i5   16      512          SSD  NaN    15.6    No   
...        ...            ...  ...      ...          ...  ...     ...   ...   
1843    Vostro  Intel Core i5    8      256          SSD  NaN    13.3    No   
1844    Vostro  Intel Core i5    8      512          SSD  NaN    13.3    No   
1845    Vostro  Intel Core i5    8      512          SSD  NaN    15.6    No   
1846       XPS  Intel Core i5    8      512          SSD  NaN    13.4    No   
1847       XPS  Intel Core i7   16      512          SSD  NaN    13.3    No   

      Final Price  
161        599.00  
271        690.15  
281        889.00  
319        789.00  
328        869.00  
...           ...  
1843       420.74  
1844       511.59  
1845       549.93  
1846       699.00  
1847      1086.88  

[84 rows x 12 columns]

In [26]:
max_dell_price = dell_laptops['Final Price'].max()
max_dell_price

3936.0

### Q6. Median value of Screen

1. Find the median value of `Screen` column in the dataset.

In [27]:
initial_mean = data['Screen'].mean()
print("Початкове середнє значення Screen:", initial_mean)

Початкове середнє значення Screen: 15.168112244897959


2. Next, calculate the most frequent value of the same `Screen` column.

In [31]:
mode_value = data['Screen'].mode()[0]  # Беремо перше значення моди, якщо їх декілька
print("Найчастіше значення Screen (мода):", mode_value)

Найчастіше значення Screen (мода): 15.6


3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.

In [32]:
data['Screen'].fillna(mode_value, inplace=True)

4. Now, calculate the median value of `Screen` once again.

In [33]:
new_mean = data['Screen'].mean()
print("Нове середнє значення Screen після заповнення пропусків:", new_mean)

Нове середнє значення Screen після заповнення пропусків: 15.168912037037037


In [34]:
if initial_mean == new_mean:
    print("Середнє значення не змінилося.")
else:
    print("Середнє значення змінилося.")

Середнє значення змінилося.


### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.

In [38]:
# Відфільтруємо дані, залишивши лише рядки, де бренд - Innjoo
innjoo_laptops = data[data['Brand'] == 'Innjoo']

# Виберемо потрібні стовпці
X = innjoo_laptops[['RAM', 'Storage', 'Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [40]:
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. Compute the inverse of `XTX`.

In [42]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [45]:
w = (XTX_inv @ X.T) @ y
w

array([45.58076606,  0.42783519, 45.29127938])

8. What's the sum of all the elements of the result?

In [47]:
res = w.sum()
print(f"Сумма элементов массива w: {res:.2f}")

Сумма элементов массива w: 91.30


> **Note**: we just implemented normal equation


$$w = (X^T X)^{-1} X^T y$$


We'll talk about it more in the next week (Machine Learning for Regression)